---
title: "PM566 Final Project"
author: "Weijia Hu"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is Weijia's PM566 Final Project website.


```{r setup, message=FALSE, echo=FALSE, warning=FALSE}
library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(DT)
library(data.table)
library(knitr)

opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = TRUE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618,
  out.width = "700px",
  class.source = "code-r")

```

```{css, echo = FALSE}
.code-r { /* Code block */
  font-size: 15px;
}

.code-r-small { /* Code block */
  font-size: 10px;
}
```

```{r load-data, echo = FALSE}
source("process_COVID_data.R")
```

```{r plot1, class.source="code-r-small", echo = FALSE}

p1_scatter <- cv_states_today %>% 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")

# filter out "District of Columbia"
cv_states_today_scatter <- cv_states_today %>% filter(state!="District of Columbia")

p2_scatter <- cv_states_today_scatter %>% 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")
```

##Lab 12 {.tabset}

### Figure 1

```{r echo=FALSE}
p1_scatter
```

### Figure 2

```{r echo=FALSE}
p2_scatter
```

{-}

```{r echo=FALSE}
library(data.table)
library(tidyverse)
library(dplyr)
library(knitr)
library(usmap)
```

```{r echo=FALSE}
cov = data.table::fread("E:/566/midterm/all-states-history.csv")
cov_d = cov[cov$dataQualityGrade=='D']
cov= cov[cov$dataQualityGrade!="D", ]
cov_1006<- cov[date=='2020-10-06']
```

```{r echo=FALSE}
cov$deathIncrease[cov$deathIncrease<0] <- NA
cov$positiveIncrease[cov$positiveIncrease<0] <- NA
```

## Assignment05 {.tabset}

### Figure 1- The bar charts of COVID-19 deaths.
```{r echo=FALSE}
cov_1006 %>%
  filter(!(death %in% NA)) %>%
  ggplot(aes(x= state, y=death, fill= state))+
  geom_bar(stat='identity')
cov_1006_1 <- cov_1006 [death>5000]
cov_1006_1$state <-reorder(cov_1006_1$state, -cov_1006_1$death)
cov_1006_1 %>%
ggplot(aes(x= state, y=death, fill= state))+
  geom_bar(stat='identity')+
  geom_text(aes(label = death , vjust = -0.8, hjust = 0.5, color = state)) 
```

### Figure 2- The map of COVID-19 deaths.

```{r echo=FALSE}
cov_1006_d = as.data.frame(cov_1006)
plot_usmap('states', data =cov_1006, values ='death')+
scale_fill_continuous(low = "pink", high = "darkred", guide = F)+
labs(title = "Total number of deaths related to Covid-19 in the USA")
```
{-}